rmrk-team/rmrk-substrate

- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-core/src/types.rs
there are a few things to consider beyond this initial implementation
- alice sends to bob's nft does not currently update bob as rootowner
- no checks are done for current owner status
> implement send w nested ownership

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/mock.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-core/src/types.rs
- runtime/src/lib.rs
- traits/src/collection.rs
- traits/src/lib.rs
This PR addresses the concerns mentioned in #24. It minimizes the generic type used in the pallets while keep the upstream `pallet-unique` integration.
Tested: cargo test
> Make the id concrete types

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
Poking around to learn and to hopefully contribute.
**Work done**
* Get next available NFT and ensure it is less than collection max
* Tests included.
It does seem to follow the specified domain logic to my understanding.
The following steps ends in a `CollectionFullOrLocked` error:
- Create collection with max = 2
- Mint 2 items into collection
- Burn one of the items
- Try to mint a third.
-  => `CollectionFullOrLocked`
**Questions:**
* Is this the desired logic?
* Should it have a distinct error enum type?
**Possible fix to #10**
> Prevent minting when next NFT id is greater than the collection max.

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
Simplify and ensure all calls are signed. Addressing #36
When / if needed we can add extra checks back (such as `ensure_protocol_or_signed`)
> Simplify ensure signed checks 

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- traits/src/collection.rs
Add `nfts_count` counter to `collection`. Increment during `mint_nft`, decrement during `burn_nft`
Changes in `src/lib.rs` purely formatting from cargo fmt
Fixes #37
> Avoid iteration when checking collection size

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/mock.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-core/src/types.rs
- pallets/uniques/src/functions.rs
- traits/src/nft.rs
* User mints an NFT with `pallet_unique::Pallet::<T>::mint(origin, owner, col, nft)?;`
* User `transfer(origin: OriginFor<T>, col: CollectionId, nft: NftId, dest: AccountIdOrNftTuple)` NFT to another NFT
* Check ownership with `lookup_root_owner(col, nft)`
* `match` `dest_account` to `AccountId(id)` if Account owner
* else if match on `NFTTuple(c,n)` then call `lookup_root_owner(c, n)` & if no circle detection triggered then convert to virtual account with `nft_to_account_id(c, n)`
* check children 
* If `origin` does transfer then auto-accept NFT & set `pending` === false
* else set NFT property `pending` === true
* Emit Event `NFTSent`
* [SEND](https://github.com/rmrk-team/rmrk-spec/blob/master/standards/rmrk2.0.0/interactions/send.md)
* …
> Lazy ownership tree based on pallet-unique's owner

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/types.rs
- traits/src/collection.rs
- traits/src/nft.rs
> Lazy Ownership Fixes

- pallets/rmrk-core/src/tests.rs
mostly just
- reorders so like-with-like (order is collection, nft, resource, property, priority)
- adds comments all over
- adds a basic_mint() function to reduce redundancy
- some consolidation of tests
> Tidy and comment tests.rs

- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
fixes #55 where we don't checking pending state on a resource before allowing it to be accepted (which is redundant but success would trigger accept events which it shouldn't)
> implement ResourceNotPending when accepting a resource that need not be accepted

- pallets/rmrk-core/src/lib.rs
> Bug #111 Minting NFT to Different Owner than Origin Still Mints to Origin

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
It looks like we're not doing anything with it anyway (besides an insert operation in the minting).  So let's just get rid of it.
Addresses #48
> remove NftsByOwner

- docs/pallets/rmrk-core.md
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/functions.rs
- pallets/rmrk-equip/src/lib.rs
- pallets/rmrk-equip/src/tests.rs
- traits/src/base.rs
> implement changeissuer for base

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/tests.rs
addresses #148, we weren't removing child from *parent* in the event of a burn.  easy fix (hopefully).
> remove parent's child when child burned

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/functions.rs
- pallets/rmrk-equip/src/lib.rs
- pallets/rmrk-equip/src/tests.rs
- traits/src/base.rs
- traits/src/resource.rs
addresses #138 
One issue that remains is that id is part of the `Resource` struct.  I don't think this is necessary generally.  For example, Nft and Collection don't have their respective IDs as part of their struct.  However, we need to extract the resource ID when doing an iter_prefix_values for the CollectionID, NftId inside the `do_equip` function (we do this when checking for the existence of a BaseId+SlotId on the resources for a Slot Resource -- that is, ensuring that there exists a Slot Resource matching the BaseId and SlotId passed to the equip extrinsic).
https://github.com/rmrk-team/rmrk-substrate/blob/218fe30a8950ab0acf51976246fcd6b812aa8a87/pallets/rmrk-equip/src/functions.rs#L255-L268
We could either figure out how to get the key value when iterating through with …
> switch to auto-increment ResourceId

- runtime/src/lib.rs
> Disable pallet uniques calls

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/tests.rs
- pallets/rmrk-market/src/lib.rs
- pallets/rmrk-market/src/tests.rs
- traits/src/nft.rs
> Non-transferable items

- pallets/rmrk-equip/src/functions.rs
- pallets/rmrk-equip/src/lib.rs
- pallets/rmrk-equip/src/tests.rs
- traits/src/base.rs
- traits/src/theme.rs
> convert Theme properties to BoundedVec

- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/tests.rs
- pallets/rmrk-market/src/tests.rs
Fixes #160
Haven't added explicit test, but it's implicit here:
https://github.com/rmrk-team/rmrk-substrate/blob/c3c969c30db6918a2477313172c4f478c949c59d/pallets/rmrk-core/src/tests.rs#L54-L57
> make owner during minting optional

- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/mock.rs
- pallets/rmrk-core/src/tests.rs
- traits/src/nft.rs
> implement max_burns for burn_nft

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/tests.rs
- pallets/rmrk-market/src/tests.rs
- traits/src/nft.rs
- traits/src/resource.rs
This is basic implementation but some missing pieces
> allow minting directly to nft

- pallets/rmrk-equip/src/functions.rs
- tests/src/equipNft.test.ts
- tests/src/removeResource.test.ts
- tests/src/util/tx.ts
> Fix RPC Equip/Unequip Logic

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/tests.rs
- traits/src/nft.rs
- traits/src/property.rs
> Create/Update Internal Functions

- node/src/benchmarking.rs
- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/mock.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/lib.rs
- pallets/rmrk-equip/src/tests.rs
- pallets/rmrk-market/src/mock.rs
- pallets/rmrk-market/src/tests.rs
- traits/src/base.rs
- traits/src/collection.rs
- traits/src/part.rs
- traits/src/phantom_type.rs
- traits/src/priority.rs
- traits/src/resource.rs
- traits/src/serialize.rs
- traits/src/theme.rs
All changes are cosmetic except replacing deprecated `remove_prefix` with `clear_prefix`. See [docs here](https://paritytech.github.io/substrate/master/frame_support/storage/trait.StorageNMap.html)
> Removing compile warnings

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/tests.rs
- tests/src/util/tx.ts
> fix issue 208 allow minting after burn

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/tests.rs
Fix bug #227 where minting directly to NFT does not update the `Children` `StorageDoubleMap` which cause the `Children` to be inconsistent.
> Bug Fix 227 Update Children storage when sending NFT directly to NFT

- pallets/rmrk-core/src/functions.rs
- pallets/rmrk-core/src/lib.rs
- pallets/rmrk-core/src/mock.rs
- pallets/rmrk-core/src/tests.rs
- pallets/rmrk-equip/src/functions.rs
- pallets/rmrk-equip/src/lib.rs
- pallets/rmrk-equip/src/mock.rs
- pallets/rmrk-equip/src/tests.rs
- pallets/rmrk-market/src/mock.rs
- runtime/src/lib.rs
- tests/src/interfaces/augment-api-tx.ts
- tests/src/util/tx.ts
- traits/src/budget.rs
- traits/src/lib.rs
- traits/src/nft.rs
> Improve nesting

- pallets/rmrk-equip/src/functions.rs
- pallets/rmrk-equip/src/lib.rs
- pallets/rmrk-equip/src/tests.rs
- tests/src/setEquippableList.test.ts
- tests/src/util/tx.ts
- traits/src/base.rs
> Equippables addition/removal feature

- runtime/src/lib.rs
Add missing cfg attribute to initialize `pallet_rmrk_equip`'s `Helper` type only under `runtime-benchmark` feature
> Add cfg attribute to runtime-benchmark Helper in pallet_equip
