rmrk-team/rmrk-substrate

pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs, pallets/rmrk-core/src/types.rs
implements lock-collection by setting max to 0.  check is implemented on max during minting.
=> expands collection per spec and implements lock-collection

pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs
get boundedvec's into the resource parameter calls.
=> convert resource to bvec

pallets/rmrk-core/src/lib.rs
adds the storage item, and works for minting
need to implement send (including iterative) and burn, and write some tests
=> add basic by-owner storage

runtime/Cargo.toml, runtime/src/lib.rs
Add support for pallet_utility to enable batches.
=> Add pallet_utility

pallets/rmrk-core/README.md
Please bear with me; I try out a small pull request to see how this works :-)
Since I don't have permissions to your repo I created a fork with a new branch 'test-coverage' where I can commit my changes. I guess once the test classes are ready for merge we find a way to move them over.
=> changed lock_collection, added destroy_collection

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs, pallets/rmrk-market/src/lib.rs, pallets/rmrk-market/src/mock.rs, pallets/rmrk-market/src/tests.rs, pallets/rmrk-market/src/types.rs
Add optional amount to buy function that can be defined to prevent front running the buy and listing the NFT at a higher price. Addresses #81
=> Fix Issue #81 Market Buy

pallets/rmrk-core/src/functions.rs
=> fix double event emission for set-property

pallets/rmrk-equip/src/functions.rs, pallets/rmrk-equip/src/lib.rs
=> docstrings and comments for equip pallet

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/mock.rs, pallets/rmrk-equip/src/mock.rs, pallets/rmrk-equip/src/tests.rs, pallets/rmrk-market/src/mock.rs, runtime/src/lib.rs, traits/src/collection.rs
fixes #38 by creating a pallet constant CollectionSymbolLimit (a u32).
=> implement CollectionSymbolLimit

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs, traits/src/collection.rs
Update bugs when setting priority, locking a collection and ensuring that uniques pallet storage is synced with the rmrk's pallet storage for collection issuer.
Fixes:
#114 
#116 
#117
=> Update Permissions Issues

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs, pallets/rmrk-equip/src/tests.rs, traits/src/nft.rs
=> implement pending for reject nft

pallets/rmrk-core/src/mock.rs, pallets/rmrk-core/src/tests.rs
addresses the missing test for #107
=> implement test for burn_nft max_recursions

pallets/rmrk-core/src/functions.rs
=> switch from drain_prefix to remove_prefix

pallets/rmrk-core/src/functions.rs
=> switch from iter_prefix to drain_prefix

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs, traits/src/lib.rs, traits/src/nft.rs
Converts internal Royalty information into a struct, tying amount and recipient together, refactors where needed, adds tests
resolves #121
=> implement royalty struct

pallets/rmrk-equip/src/tests.rs, traits/src/theme.rs
=> move inherit from ThemeProperty to Theme

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/tests.rs
=> fix reject so it murders Children struct too

Cargo.lock, node/Cargo.toml, node/src/rpc.rs, pallets/rmrk-core/Cargo.toml, pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/mock.rs, pallets/rmrk-equip/Cargo.toml, pallets/rmrk-equip/src/functions.rs, pallets/rmrk-equip/src/lib.rs, pallets/rmrk-equip/src/mock.rs, pallets/rmrk-market/Cargo.toml, pallets/rmrk-market/src/lib.rs, pallets/rmrk-market/src/mock.rs, pallets/template/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs, traits/Cargo.toml
Changes to upgrade to `polkadot-v0.9.23`
=> Upgrade to Polkadot v0.9.23

pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/mock.rs, pallets/rmrk-core/src/tests.rs, pallets/rmrk-equip/src/mock.rs, pallets/rmrk-equip/src/tests.rs, pallets/rmrk-market/src/mock.rs, pallets/rmrk-market/src/tests.rs, runtime/src/lib.rs
=> allow adding resources on mint

pallets/rmrk-equip/src/tests.rs, traits/src/part.rs
=> make slot part src optional

pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs, pallets/rmrk-equip/src/tests.rs
=> remove unused resource ID argument

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-equip/src/functions.rs
=> change name of slot and composable resource storage

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-core/src/tests.rs
=> implement error CannotRejectNonPendingNft

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/lib.rs, pallets/rmrk-equip/src/tests.rs
=> prevent send for equipped item

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/tests.rs, pallets/rmrk-equip/src/tests.rs, traits/src/resource.rs
=> allow composable resources to also be equippable

Cargo.lock, node/Cargo.toml, pallets/rmrk-core/Cargo.toml, pallets/rmrk-equip/Cargo.toml, pallets/rmrk-market/Cargo.toml, pallets/template/Cargo.toml, rpc-runtime-api/Cargo.toml, rpc/Cargo.toml, runtime/Cargo.toml, traits/Cargo.toml
Upgrade to `polkadot-v0.9.28` and the `jsonrpsee` to `0.15.1`
=> Upgrade to polkadot-v0.9.28

pallets/rmrk-market/src/lib.rs
=> remove unnecessary check in list

pallets/rmrk-core/src/functions.rs, pallets/rmrk-core/src/tests.rs
attempts to address #191.  i think it's successful.
=> fix 191 resource removal

pallets/rmrk-core/src/functions.rs, pallets/rmrk-equip/src/functions.rs, pallets/rmrk-equip/src/lib.rs
=> Safety pass: avoid usage of unwrap
